version: "3"
volumes:
  node_modules:
services:
  firesmoke:
    environment:
      - env=dev
    build:
      context: .
      dockerfile: ./firesmoke/Dockerfile.Development
    volumes:
      - ./firesmoke/:/usr/src/app
      - ./firesmoke/node_modules:/usr/src/app/node_modules
    ports:
      - "3010:3000"
    restart: always
